export const CHART_SIZE_CHANGE = 'CHART_SIZE_CHANGE';
export const HEIGHT_CHANGE = 'HEIGHT_CHANGE';
export const RADIUS_CHANGE = 'RADIUS_CHANGE';
export const ANGLE_CHANGE = 'ANGLE_CHANGE';
export const DURATION_CHANGE = 'DURATION_CHANGE';
export const FONT_SIZE_CHANGE = 'FONT_SIZE_CHANGE';
export const TOGGLE_ANIMATION = 'TOGGLE_ANIMATION';
export const TOGGLE_SLICE_SELECT = 'TOGGLE_SLICE_SELECT';
export const TOGGLE_LABEL = 'TOGGLE_LABEL';
export const TOGGLE_LABEL_COLOR = 'TOGGLE_LABEL_COLOR';
export const TOGGLE_TOOLTIP = 'TOGGLE_TOOLTIP';

export const ADD_ROW = 'ADD_ROW';
export const DELETE_ROW = 'DELETE_ROW';
export const COLOR_CHANGE = 'COLOR_CHANGE';
export const LABEL_CHANGE = 'LABEL_CHANGE';
export const VALUE_CHANGE = 'VALUE_CHANGE';
